### ISSUE TITLE
Suggested additional book as described in my L/i post

### ISSUE THREAD

**Issue by tmcmast** [AbductiveReason/AwesomePrivacyEngineering#1]
[The Privacy Engineer's Manifesto](https://www.apress.com/us/book/9781430263555) by Michelle Finneran Dennedy et al. ([Dr. Ann Cavoukian, Ph.D.](https://en.wikipedia.org/wiki/Ann_Cavoukian), contributing.

**Comment by AbductiveReason** [comment]
Added. Thank you for the suggestion.
