### ISSUE TITLE
Minor -- Proposed modification to Dr. Cavoukian link (title) 

### ISSUE THREAD

**Issue by tmcmast** [AbductiveReason/AwesomePrivacyEngineering#2]
Consider modifying text in link to Dr. Cavoukian in intro section to use Dr. Cavoukian's full title, "[Dr. Ann Cavoukian]( https://www.ryerson.ca/pbdce/about/ann-cavoukian/ )," and/or link to her current professor bio page here rather than Wikipedia page: https://www.ryerson.ca/pbdce/about/ann-cavoukian/

**Comment by AbductiveReason** [comment]
Thank you for the clarification. Dr. Ann's information has been updated.
