### ISSUE TITLE
Suggestion for a book(let) to add.

### ISSUE THREAD

**Issue by xot** [AbductiveReason/AwesomePrivacyEngineering#4]
J.-H. Hoepman. Privacy Design Strategies. The Little Blue Book, May, 2018.
https://www.cs.ru.nl/~jhh/publications/pds-booklet.pdf

**Comment by tmcmast** [comment]
Really liked Dr. Hoepman's (@xot) publication -- a great high-level description of PE concepts that should be easily accessible to non-technical people, and to some extent could be said to get around the edges of OWASP Top 10 stuff. Most of the publications I see that are intended to break things down for non-technical folk strike me as actually potentially fairly overwhelming, but this is an easily digestible book that actually seems to explain things at a fairly sophisticated level. I need to review it more extensively, but I think this may well be my go-to resource for explaining PE to non-technical colleagues going forward -- from the co-birthplace of PE!

**Comment by AbductiveReason** [comment]
Added a few months ago.
